version: "3"
services:

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:rpoder
    env_file: .env
    networks:
      - inception_network
    build:
      context: srcs/requirements/nginx
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"

  mariadb:
    build:
      context: ./srcs/requirements/mariadb
    container_name: mariadb
    hostname: mariadb
    image: mariadb:rpoder
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysql $SQL_DATABASE_NAME -uroot -p$SQL_ROOT_PASSWORD -e 'SELECT 1' || exit 1"]
      interval: 0.5s
      retries: 100

  wordpress:
    container_name: wordpress
    hostname: wordpress
    image: wordpress:rpoder
    env_file: .env
    networks:
      - inception_network
    build:
      context: srcs/requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      mariadb:
          condition: service_healthy
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/rpoder/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/rpoder/data/mariadb
      o: bind
      type: none

networks:
  inception_network:
    name: inception_network
    driver: bridge
