version: "3"
services:

  nginx:
    container_name: nginx
    hostname: nginx
    env_file: .env
    networks:
      - inception_network
    build:
      context: srcs/requirements/nginx
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: on-failure
    ports:
      - "443:443"

  mariadb:
    build:
      context: ./srcs/requirements/mariadb
    container_name: mariadb
    hostname: mariadb
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    hostname: wordpress
    env_file: .env
    networks:
      - inception_network
    build:
      context: srcs/requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    restart: on-failure

  # php:
  #     container_name: php
  #     env_file: .env
  #     networks:
  #       - inception_network
  #     build:
  #       context: srcs/requirements/php
  #     volumes:
  #       - wordpress:/var/www/wordpress
  #     restart: on-failure
  #     ports:
  #       - "9000"


volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/rpoder/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/rpoder/data/mariadb
      o: bind
      type: none

networks:
  inception_network:
    name: inception_network
    driver: bridge
